version: "3"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/fytics/frontend
      - node-modules:/fytics/frontend/node_modules
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/fytics/backend
    ports:
      - 8000:8000
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    build: ./nginx/
    ports:
      - "60:60"
    links:
      - backend:backend
volumes:
 node-modules:
